//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriceCheck.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow keybind to be pressed after hovering over item.
        /// </summary>
        internal static string AllowKeybindAfterHover {
            get {
                return ResourceManager.GetString("AllowKeybindAfterHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allows you to hold the keybind after the item tooltip has been opened (disable for legacy mode).
        /// </summary>
        internal static string AllowKeybindAfterHover_HelpMarker {
            get {
                return ResourceManager.GetString("AllowKeybindAfterHover_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        internal static string AveragePrice {
            get {
                return ResourceManager.GetString("AveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average sale price in recent sale history with outliers removed beyond three standard deviations of the mean..
        /// </summary>
        internal static string AveragePriceDesc {
            get {
                return ResourceManager.GetString("AveragePriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below minimum price.
        /// </summary>
        internal static string BelowMinimum {
            get {
                return ResourceManager.GetString("BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell to vendor.
        /// </summary>
        internal static string BelowVendor {
            get {
                return ResourceManager.GetString("BelowVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat channel.
        /// </summary>
        internal static string ChatChannel {
            get {
                return ResourceManager.GetString("ChatChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set the chat channel to send messages.
        /// </summary>
        internal static string ChatChannel_HelpMarker {
            get {
                return ResourceManager.GetString("ChatChannel_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear items.
        /// </summary>
        internal static string ClearPricedItems {
            get {
                return ResourceManager.GetString("ClearPricedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Average Price.
        /// </summary>
        internal static string CurrentAveragePrice {
            get {
                return ResourceManager.GetString("CurrentAveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average sale price in current listings with outliers removed beyond three standard deviations of the mean..
        /// </summary>
        internal static string CurrentAveragePriceDesc {
            get {
                return ResourceManager.GetString("CurrentAveragePriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Minimum Price.
        /// </summary>
        internal static string CurrentMinimumPrice {
            get {
                return ResourceManager.GetString("CurrentMinimumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum price in current listings across both normal and high quality items..
        /// </summary>
        internal static string CurrentMinimumPriceDesc {
            get {
                return ResourceManager.GetString("CurrentMinimumPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string DisplayHeading {
            get {
                return ResourceManager.GetString("DisplayHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data (universalis.app may be down).
        /// </summary>
        internal static string FailedToGetData {
            get {
                return ResourceManager.GetString("FailedToGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process item.
        /// </summary>
        internal static string FailedToProcess {
            get {
                return ResourceManager.GetString("FailedToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FiltersHeading {
            get {
                return ResourceManager.GetString("FiltersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To check prices, hold your keybind and then hover over an item in your inventory or linked in chat. You can set your keybind (or disable it) in the PriceCheck settings. The prices are averages from Universalis and will not match any specific listings you see on the market board. You can use /pcheck to open the overlay and /pcheckconfig to open settings. If you need help, reach out on discord or open an issue on GitHub. If you want to help add translations, you can submit updates on Crowdin..
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide overlay timer.
        /// </summary>
        internal static string HideOverlayTimer {
            get {
                return ResourceManager.GetString("HideOverlayTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide overlay after x amount of seconds since last price check - you can this by setting to zero..
        /// </summary>
        internal static string HideOverlayTimer_HelpMarker {
            get {
                return ResourceManager.GetString("HideOverlayTimer_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover delay.
        /// </summary>
        internal static string HoverDelay {
            get {
                return ResourceManager.GetString("HoverDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delay (in seconds) before processing after hovering.
        /// </summary>
        internal static string HoverDelay_HelpMarker {
            get {
                return ResourceManager.GetString("HoverDelay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing PriceCheck!.
        /// </summary>
        internal static string InstallThankYou {
            get {
                return ResourceManager.GetString("InstallThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind.
        /// </summary>
        internal static string Keybind {
            get {
                return ResourceManager.GetString("Keybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable keybind.
        /// </summary>
        internal static string KeybindEnabled {
            get {
                return ResourceManager.GetString("KeybindEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle if keybind is used or just hover.
        /// </summary>
        internal static string KeybindEnabled_HelpMarker {
            get {
                return ResourceManager.GetString("KeybindEnabled_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Price.
        /// </summary>
        internal static string MaximumPrice {
            get {
                return ResourceManager.GetString("MaximumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum price in current listings..
        /// </summary>
        internal static string MaximumPriceDesc {
            get {
                return ResourceManager.GetString("MaximumPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max items.
        /// </summary>
        internal static string MaxItems {
            get {
                return ResourceManager.GetString("MaxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set max number of items in overlay at a time.
        /// </summary>
        internal static string MaxItems_HelpMarker {
            get {
                return ResourceManager.GetString("MaxItems_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Upload Days.
        /// </summary>
        internal static string MaxUploadDays {
            get {
                return ResourceManager.GetString("MaxUploadDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set maximum age to avoid using old data.
        /// </summary>
        internal static string MaxUploadDays_HelpMarker {
            get {
                return ResourceManager.GetString("MaxUploadDays_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Price.
        /// </summary>
        internal static string MinimumPrice {
            get {
                return ResourceManager.GetString("MinimumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set minimum price at which actual average will be displayed.
        /// </summary>
        internal static string MinimumPrice_HelpMarker {
            get {
                return ResourceManager.GetString("MinimumPrice_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum price in current listings..
        /// </summary>
        internal static string MinimumPriceDesc {
            get {
                return ResourceManager.GetString("MinimumPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string ModifierKeybind {
            get {
                return ResourceManager.GetString("ModifierKeybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set your modifier key (e.g. shift).
        /// </summary>
        internal static string ModifierKeybind_HelpMarker {
            get {
                return ResourceManager.GetString("ModifierKeybind_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent data.
        /// </summary>
        internal static string NoRecentDataAvailable {
            get {
                return ResourceManager.GetString("NoRecentDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceCheck is disabled..
        /// </summary>
        internal static string PluginDisabled {
            get {
                return ResourceManager.GetString("PluginDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin enabled.
        /// </summary>
        internal static string PluginEnabled {
            get {
                return ResourceManager.GetString("PluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle the plugin on/off.
        /// </summary>
        internal static string PluginEnabled_HelpMarker {
            get {
                return ResourceManager.GetString("PluginEnabled_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price mode.
        /// </summary>
        internal static string PriceMode {
            get {
                return ResourceManager.GetString("PriceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select price calculation to use.
        /// </summary>
        internal static string PriceMode_HelpMarker {
            get {
                return ResourceManager.GetString("PriceMode_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string PrimaryKeybind {
            get {
                return ResourceManager.GetString("PrimaryKeybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set your primary key (e.g. None, Z).
        /// </summary>
        internal static string PrimaryKeybind_HelpMarker {
            get {
                return ResourceManager.GetString("PrimaryKeybind_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t process in combat.
        /// </summary>
        internal static string RestrictInCombat {
            get {
                return ResourceManager.GetString("RestrictInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t process price checks while in combat.
        /// </summary>
        internal static string RestrictInCombat_HelpMarker {
            get {
                return ResourceManager.GetString("RestrictInCombat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t process in content.
        /// </summary>
        internal static string RestrictInContent {
            get {
                return ResourceManager.GetString("RestrictInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t process price checks while in content.
        /// </summary>
        internal static string RestrictInContent_HelpMarker {
            get {
                return ResourceManager.GetString("RestrictInContent_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell on marketboard.
        /// </summary>
        internal static string SellOnMarketboard {
            get {
                return ResourceManager.GetString("SellOnMarketboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cheaper than minimum threshold warning.
        /// </summary>
        internal static string ShowBelowMinimumInChat {
            get {
                return ResourceManager.GetString("ShowBelowMinimumInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning the price is below your minimum threshold.
        /// </summary>
        internal static string ShowBelowMinimumInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowBelowMinimumInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cheaper than minimum threshold warning.
        /// </summary>
        internal static string ShowBelowMinimumInOverlay {
            get {
                return ResourceManager.GetString("ShowBelowMinimumInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning the price is below your minimum threshold.
        /// </summary>
        internal static string ShowBelowMinimumInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowBelowMinimumInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cheaper than vendor price warning.
        /// </summary>
        internal static string ShowBelowVendorInChat {
            get {
                return ResourceManager.GetString("ShowBelowVendorInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning that the market price is cheaper than what you can sell it to a vendor for.
        /// </summary>
        internal static string ShowBelowVendorInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowBelowVendorInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cheaper than vendor price warning.
        /// </summary>
        internal static string ShowBelowVendorInOverlay {
            get {
                return ResourceManager.GetString("ShowBelowVendorInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning that the market price is cheaper than what you can sell it to a vendor for.
        /// </summary>
        internal static string ShowBelowVendorInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowBelowVendorInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show context menu.
        /// </summary>
        internal static string ShowContextMenu {
            get {
                return ResourceManager.GetString("ShowContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show failed to get data error.
        /// </summary>
        internal static string ShowFailedToGetDataInChat {
            get {
                return ResourceManager.GetString("ShowFailedToGetDataInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show error where the plugin couldn&apos;t connect to universalis to get the data - usually a problem with your connection or universalis is down.
        /// </summary>
        internal static string ShowFailedToGetDataInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowFailedToGetDataInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show failed to get data error.
        /// </summary>
        internal static string ShowFailedToGetDataInOverlay {
            get {
                return ResourceManager.GetString("ShowFailedToGetDataInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show error where the plugin couldn&apos;t connect to universalis to get the data - usually a problem with your connection or universalis is down.
        /// </summary>
        internal static string ShowFailedToGetDataInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowFailedToGetDataInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show failed to process error.
        /// </summary>
        internal static string ShowFailedToProcessInChat {
            get {
                return ResourceManager.GetString("ShowFailedToProcessInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show error where something went wrong unexpectedly.
        /// </summary>
        internal static string ShowFailedToProcessInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowFailedToProcessInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show failed to process error.
        /// </summary>
        internal static string ShowFailedToProcessInOverlay {
            get {
                return ResourceManager.GetString("ShowFailedToProcessInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show error where something went wrong unexpectedly.
        /// </summary>
        internal static string ShowFailedToProcessInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowFailedToProcessInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in chat.
        /// </summary>
        internal static string ShowInChat {
            get {
                return ResourceManager.GetString("ShowInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show price check results in chat.
        /// </summary>
        internal static string ShowInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show keybind in titlebar.
        /// </summary>
        internal static string ShowKeybindInTitleBar {
            get {
                return ResourceManager.GetString("ShowKeybindInTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle if keybind is displayed in titlebar.
        /// </summary>
        internal static string ShowKeybindInTitleBar_HelpMarker {
            get {
                return ResourceManager.GetString("ShowKeybindInTitleBar_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show no data available warning.
        /// </summary>
        internal static string ShowNoDataAvailableInChat {
            get {
                return ResourceManager.GetString("ShowNoDataAvailableInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning where there was no data from universalis available for the item.
        /// </summary>
        internal static string ShowNoDataAvailableInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowNoDataAvailableInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show no data available warning.
        /// </summary>
        internal static string ShowNoDataAvailableInOverlay {
            get {
                return ResourceManager.GetString("ShowNoDataAvailableInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning where there was no data from universalis available for the item.
        /// </summary>
        internal static string ShowNoDataAvailableInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowNoDataAvailableInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show no recent data available warning.
        /// </summary>
        internal static string ShowNoRecentDataAvailableInChat {
            get {
                return ResourceManager.GetString("ShowNoRecentDataAvailableInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning where there was no recent data from universalis available for the item within your threshold.
        /// </summary>
        internal static string ShowNoRecentDataAvailableInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowNoRecentDataAvailableInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show no recent data available warning.
        /// </summary>
        internal static string ShowNoRecentDataAvailableInOverlay {
            get {
                return ResourceManager.GetString("ShowNoRecentDataAvailableInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning where there was no recent data from universalis available for the item within your threshold.
        /// </summary>
        internal static string ShowNoRecentDataAvailableInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowNoRecentDataAvailableInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show overlay.
        /// </summary>
        internal static string ShowOverlay {
            get {
                return ResourceManager.GetString("ShowOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show price check results in overlay window.
        /// </summary>
        internal static string ShowOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show overlay by keybind.
        /// </summary>
        internal static string ShowOverlayByKeybind {
            get {
                return ResourceManager.GetString("ShowOverlayByKeybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show overlay window when keybind is being held.
        /// </summary>
        internal static string ShowOverlayByKeybind_HelpMarker {
            get {
                return ResourceManager.GetString("ShowOverlayByKeybind_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show overlay on login.
        /// </summary>
        internal static string ShowOverlayOnLogin {
            get {
                return ResourceManager.GetString("ShowOverlayOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show overlay window on login.
        /// </summary>
        internal static string ShowOverlayOnLogin_HelpMarker {
            get {
                return ResourceManager.GetString("ShowOverlayOnLogin_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show prices.
        /// </summary>
        internal static string ShowPrices {
            get {
                return ResourceManager.GetString("ShowPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show price or just show advice.
        /// </summary>
        internal static string ShowPrices_HelpMarker {
            get {
                return ResourceManager.GetString("ShowPrices_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show successful price check.
        /// </summary>
        internal static string ShowSuccessInChat {
            get {
                return ResourceManager.GetString("ShowSuccessInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show successful price check.
        /// </summary>
        internal static string ShowSuccessInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowSuccessInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show successful price check.
        /// </summary>
        internal static string ShowSuccessInOverlay {
            get {
                return ResourceManager.GetString("ShowSuccessInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show successful price check.
        /// </summary>
        internal static string ShowSuccessInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowSuccessInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toast.
        /// </summary>
        internal static string ShowToast {
            get {
                return ResourceManager.GetString("ShowToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show price check results in toasts.
        /// </summary>
        internal static string ShowToast_HelpMarker {
            get {
                return ResourceManager.GetString("ShowToast_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unmarketable warning.
        /// </summary>
        internal static string ShowUnmarketableInChat {
            get {
                return ResourceManager.GetString("ShowUnmarketableInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning that the item can&apos;t be sold on the market board.
        /// </summary>
        internal static string ShowUnmarketableInChat_HelpMarker {
            get {
                return ResourceManager.GetString("ShowUnmarketableInChat_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unmarketable warning.
        /// </summary>
        internal static string ShowUnmarketableInOverlay {
            get {
                return ResourceManager.GetString("ShowUnmarketableInOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show warning that the item can&apos;t be sold on the market board.
        /// </summary>
        internal static string ShowUnmarketableInOverlay_HelpMarker {
            get {
                return ResourceManager.GetString("ShowUnmarketableInOverlay_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string StyleHeading {
            get {
                return ResourceManager.GetString("StyleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thresholds.
        /// </summary>
        internal static string Thresholds {
            get {
                return ResourceManager.GetString("Thresholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceCheck ({0}).
        /// </summary>
        internal static string TitleBarWithKeybind1 {
            get {
                return ResourceManager.GetString("TitleBarWithKeybind1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceCheck ({0}+{1}).
        /// </summary>
        internal static string TitleBarWithKeybind2 {
            get {
                return ResourceManager.GetString("TitleBarWithKeybind2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast.
        /// </summary>
        internal static string Toast {
            get {
                return ResourceManager.GetString("Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t sell on marketboard.
        /// </summary>
        internal static string Unmarketable {
            get {
                return ResourceManager.GetString("Unmarketable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use chat colors.
        /// </summary>
        internal static string UseChatColors {
            get {
                return ResourceManager.GetString("UseChatColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use different colors for chat based on result.
        /// </summary>
        internal static string UseChatColors_HelpMarker {
            get {
                return ResourceManager.GetString("UseChatColors_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use item links.
        /// </summary>
        internal static string UseItemLinks {
            get {
                return ResourceManager.GetString("UseItemLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use item links in chat results.
        /// </summary>
        internal static string UseItemLinks_HelpMarker {
            get {
                return ResourceManager.GetString("UseItemLinks_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use overlay colors.
        /// </summary>
        internal static string UseOverlayColors {
            get {
                return ResourceManager.GetString("UseOverlayColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use different colors for overlay based on result.
        /// </summary>
        internal static string UseOverlayColors_HelpMarker {
            get {
                return ResourceManager.GetString("UseOverlayColors_HelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for items..
        /// </summary>
        internal static string WaitingForItems {
            get {
                return ResourceManager.GetString("WaitingForItems", resourceCulture);
            }
        }
    }
}
