name: Build plugin

on:
  push:

env:
  PLUGIN_NAME: PriceCheck

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET for Build
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Restore dependencies
        run: dotnet restore ./src
          
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      
      - name: Build
        run: |
          dotnet build ./src --no-restore --configuration Release --nologo /property:Version=${{steps.gitversion.outputs.MajorMinorPatch}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: |
            ./src/${{env.PLUGIN_NAME}}/bin/Release/net48/${{env.PLUGIN_NAME}}/*
            
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.gitversion.outputs.FullSemVer}}
          release_name: ${{env.PLUGIN_NAME}} ${{steps.gitversion.outputs.MajorMinorPatch}}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./src/${{env.PLUGIN_NAME}}/bin/Release/net48/${{env.PLUGIN_NAME}}/${{env.PLUGIN_NAME}}.json
          asset_name: ${{env.PLUGIN_NAME}}.zip
          asset_content_type: application/zip